// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See VDotProdUnit.h for the primary calling header

#ifndef VERILATED_VDOTPRODUNIT_FADD_H_
#define VERILATED_VDOTPRODUNIT_FADD_H_  // guard

#include "verilated.h"


class VDotProdUnit__Syms;

class alignas(VL_CACHE_LINE_BYTES) VDotProdUnit_FADD final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_OUT8(io_in_ready,0,0);
        VL_IN8(io_in_valid,0,0);
        VL_IN8(io_in_bits_roundingMode,2,0);
        VL_IN8(io_in_bits_a_inter_valid,0,0);
        VL_IN8(io_in_bits_b_inter_valid,0,0);
        VL_IN8(io_in_bits_a_inter_flags_isNaN,0,0);
        VL_IN8(io_in_bits_a_inter_flags_isInf,0,0);
        VL_IN8(io_in_bits_a_inter_flags_isInv,0,0);
        VL_IN8(io_in_bits_b_inter_flags_isNaN,0,0);
        VL_IN8(io_in_bits_b_inter_flags_isInf,0,0);
        VL_IN8(io_in_bits_b_inter_flags_isInv,0,0);
        VL_IN8(io_out_ready,0,0);
        VL_OUT8(io_out_valid,0,0);
        VL_OUT8(io_out_bits_fflags,4,0);
        CData/*7:0*/ __PVT__farPath_io_in_a_exp;
        CData/*7:0*/ __PVT__farPath_io_in_b_exp;
        CData/*0:0*/ __PVT__farPath_io_in_addSig;
        CData/*0:0*/ __PVT__farPath_io_in_tinyAdd;
        CData/*0:0*/ __PVT__farPath_io_out_far_path_of;
        CData/*0:0*/ __PVT__farPath_io_out_far_path_ix;
        CData/*0:0*/ __PVT__closePath_io_out_near_path_ix;
        CData/*0:0*/ __PVT__decode_a___05FisInf;
        CData/*0:0*/ __PVT__decode_a___05FisNaN;
        CData/*0:0*/ __PVT__decode_b___05FisInf;
        CData/*0:0*/ __PVT__decode_b___05FisNaN;
        CData/*7:0*/ __PVT__raw_a_exp;
        CData/*7:0*/ __PVT__raw_b_exp;
        CData/*0:0*/ __PVT__needSwap;
        CData/*7:0*/ __PVT__diffExp;
        CData/*0:0*/ __PVT__closePathSel;
        CData/*0:0*/ __PVT__special_path_hasNaN;
        CData/*0:0*/ __PVT__special_path_inf_iv;
        CData/*0:0*/ __PVT__special_case_happen;
        CData/*0:0*/ __PVT__rmin;
        CData/*0:0*/ __PVT__common_overflow;
        CData/*4:0*/ __PVT__farPath__DOT__shiftRightJam_io_shamt;
        CData/*0:0*/ __PVT__farPath__DOT__far_path_rounder_io_cout;
        CData/*7:0*/ __PVT__farPath__DOT__resultExpNoRound;
        CData/*0:0*/ __PVT__farPath__DOT__far_path_may_of;
        CData/*0:0*/ __PVT__farPath__DOT__far_path_tininess_rounder__DOT__rounder_io_signIn;
        CData/*0:0*/ __PVT__farPath__DOT__far_path_tininess_rounder__DOT__rounder__DOT__inexact;
        CData/*0:0*/ __PVT__farPath__DOT__far_path_rounder__DOT__inexact;
        CData/*0:0*/ __PVT__farPath__DOT__far_path_rounder__DOT__r_up;
        CData/*7:0*/ __PVT__closePath__DOT__resultExpNoRound;
        CData/*0:0*/ __PVT__closePath__DOT__shiftLimit;
        CData/*7:0*/ __PVT__closePath__DOT__sigShiftNum;
        CData/*7:0*/ __PVT__closePath__DOT__near_path_exp_rounded;
        CData/*0:0*/ __PVT__closePath__DOT___io_out_result_T_3;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector_io_y;
        CData/*4:0*/ __PVT__closePath__DOT__lza__DOT__io_lzc_lzc_io_out;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__preEncoder__DOT___f_0_T_10;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__preEncoder__DOT___f_1_T_7;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__preEncoder__DOT__f_1;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__preEncoder__DOT___f_2_T_7;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__preEncoder__DOT__f_2;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__preEncoder__DOT___f_3_T_7;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__preEncoder__DOT__f_3;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__preEncoder__DOT___f_4_T_7;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__preEncoder__DOT__f_4;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__preEncoder__DOT___f_5_T_7;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__preEncoder__DOT__f_5;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__preEncoder__DOT___f_6_T_7;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__preEncoder__DOT__f_6;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__preEncoder__DOT___f_7_T_7;
    };
    struct {
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__preEncoder__DOT__f_7;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__preEncoder__DOT___f_8_T_7;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__preEncoder__DOT__f_8;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__preEncoder__DOT___f_9_T_7;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__preEncoder__DOT__f_9;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__preEncoder__DOT___f_10_T_7;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__preEncoder__DOT__f_10;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__preEncoder__DOT___f_11_T_7;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__preEncoder__DOT__f_11;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__preEncoder__DOT___f_12_T_7;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__preEncoder__DOT__f_12;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__preEncoder__DOT___f_13_T_7;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__preEncoder__DOT__f_13;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__preEncoder__DOT___f_14_T_7;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__preEncoder__DOT__f_14;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__preEncoder__DOT___f_15_T_7;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__preEncoder__DOT__f_15;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__preEncoder__DOT___f_16_T_7;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__preEncoder__DOT__f_16;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__preEncoder__DOT___f_17_T_7;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__preEncoder__DOT__f_17;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__preEncoder__DOT___f_18_T_7;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__preEncoder__DOT__f_18;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__preEncoder__DOT___f_19_T_7;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__preEncoder__DOT__f_19;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__preEncoder__DOT___f_20_T_7;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__preEncoder__DOT__f_20;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__preEncoder__DOT___f_21_T_7;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__preEncoder__DOT__f_21;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__preEncoder__DOT___f_22_T_7;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__preEncoder__DOT__f_22;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__preEncoder__DOT___f_23_T_7;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__preEncoder__DOT__f_23;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__preEncoder__DOT__f_24;
        CData/*0:0*/ closePath__DOT__lza__DOT__preEncoder__DOT____VdfgTmp_h2d3c9525__0;
        CData/*0:0*/ closePath__DOT__lza__DOT__preEncoder__DOT____VdfgTmp_hc175800c__0;
        CData/*0:0*/ closePath__DOT__lza__DOT__preEncoder__DOT____VdfgTmp_h2df0e46a__0;
        CData/*0:0*/ closePath__DOT__lza__DOT__preEncoder__DOT____VdfgTmp_hc10ff133__0;
        CData/*0:0*/ closePath__DOT__lza__DOT__preEncoder__DOT____VdfgTmp_h2dccb4ff__0;
        CData/*0:0*/ closePath__DOT__lza__DOT__preEncoder__DOT____VdfgTmp_hc10ba7a6__0;
        CData/*0:0*/ closePath__DOT__lza__DOT__preEncoder__DOT____VdfgTmp_h2dc877d5__0;
        CData/*0:0*/ closePath__DOT__lza__DOT__preEncoder__DOT____VdfgTmp_hc10742be__0;
        CData/*0:0*/ closePath__DOT__lza__DOT__preEncoder__DOT____VdfgTmp_h2dc406a0__0;
        CData/*0:0*/ closePath__DOT__lza__DOT__preEncoder__DOT____VdfgTmp_hc103758b__0;
        CData/*0:0*/ closePath__DOT__lza__DOT__preEncoder__DOT____VdfgTmp_h2dc0558f__0;
        CData/*0:0*/ closePath__DOT__lza__DOT__preEncoder__DOT____VdfgTmp_hc11f6654__0;
        CData/*0:0*/ closePath__DOT__lza__DOT__preEncoder__DOT____VdfgTmp_h2dc36d7a__0;
        CData/*0:0*/ closePath__DOT__lza__DOT__preEncoder__DOT____VdfgTmp_hc11a1021__0;
        CData/*0:0*/ closePath__DOT__lza__DOT__preEncoder__DOT____VdfgTmp_h2ddfa237__0;
        CData/*0:0*/ closePath__DOT__lza__DOT__preEncoder__DOT____VdfgTmp_hc116b50e__0;
        CData/*0:0*/ closePath__DOT__lza__DOT__preEncoder__DOT____VdfgTmp_h2dd5f32a__0;
        CData/*0:0*/ closePath__DOT__lza__DOT__preEncoder__DOT____VdfgTmp_hc1ece003__0;
        CData/*0:0*/ closePath__DOT__lza__DOT__preEncoder__DOT____VdfgTmp_h2d10c4dd__0;
        CData/*0:0*/ closePath__DOT__lza__DOT__preEncoder__DOT____VdfgTmp_hc12fd1f4__0;
        CData/*0:0*/ closePath__DOT__lza__DOT__preEncoder__DOT____VdfgTmp_h2dec9530__0;
        CData/*0:0*/ closePath__DOT__lza__DOT__preEncoder__DOT____VdfgTmp_hc12b80e9__0;
        CData/*0:0*/ closePath__DOT__lza__DOT__preEncoder__DOT____VdfgTmp_h2def5052__0;
        CData/*0:0*/ closePath__DOT__lza__DOT__preEncoder__DOT____VdfgTmp_hc126a535__0;
        CData/*0:0*/ closePath__DOT__lza__DOT__preEncoder__DOT____VdfgTmp_h2deb60af__0;
        CData/*0:0*/ closePath__DOT__lza__DOT__preEncoder__DOT____VdfgTmp_hc1225580__0;
        CData/*0:0*/ closePath__DOT__lza__DOT__preEncoder__DOT____VdfgTmp_h2de730f8__0;
        CData/*0:0*/ closePath__DOT__lza__DOT__preEncoder__DOT____VdfgTmp_hc13ec59f__0;
        CData/*0:0*/ closePath__DOT__lza__DOT__preEncoder__DOT____VdfgTmp_h2de3c335__0;
        CData/*0:0*/ closePath__DOT__lza__DOT__preEncoder__DOT____VdfgTmp_hc13af6ea__0;
    };
    struct {
        CData/*0:0*/ closePath__DOT__lza__DOT__preEncoder__DOT____VdfgTmp_h2df88965__0;
        CData/*0:0*/ closePath__DOT__lza__DOT__preEncoder__DOT____VdfgTmp_hc137964c__0;
        CData/*0:0*/ closePath__DOT__lza__DOT__preEncoder__DOT____VdfgTmp_h2df4d070__0;
        CData/*0:0*/ closePath__DOT__lza__DOT__preEncoder__DOT____VdfgTmp_hc133bf59__0;
        CData/*0:0*/ closePath__DOT__lza__DOT__preEncoder__DOT____VdfgTmp_h2db0aa3f__0;
        CData/*0:0*/ closePath__DOT__lza__DOT__preEncoder__DOT____VdfgTmp_hc1c9b7e6__0;
        CData/*0:0*/ closePath__DOT__lza__DOT__preEncoder__DOT____VdfgTmp_h2d8d732a__0;
        CData/*0:0*/ closePath__DOT__lza__DOT__preEncoder__DOT____VdfgTmp_hc1c59ef3__0;
        CData/*0:0*/ closePath__DOT__lza__DOT__preEncoder__DOT____VdfgTmp_h2d88ba00__0;
        CData/*0:0*/ closePath__DOT__lza__DOT__preEncoder__DOT____VdfgTmp_hc1c186eb__0;
        CData/*0:0*/ closePath__DOT__lza__DOT__preEncoder__DOT____VdfgTmp_h2d854375__0;
        CData/*0:0*/ closePath__DOT__lza__DOT__preEncoder__DOT____VdfgTmp_hc1ddae5e__0;
        CData/*0:0*/ closePath__DOT__lza__DOT__preEncoder__DOT____VdfgTmp_h2d8119da__0;
        CData/*0:0*/ closePath__DOT__lza__DOT__preEncoder__DOT____VdfgTmp_hc1de2a81__0;
        CData/*0:0*/ closePath__DOT__lza__DOT__preEncoder__DOT____VdfgTmp_h2dacef2f__0;
        CData/*0:0*/ closePath__DOT__lza__DOT__preEncoder__DOT____VdfgTmp_hc1e5c2f4__0;
        CData/*1:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node0_io_out_0;
        CData/*1:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node0_io_out_2;
        CData/*1:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node_1_io_out_0;
        CData/*1:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node_1_io_out_2;
        CData/*1:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node_2_io_out_0;
        CData/*1:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node_2_io_out_2;
        CData/*1:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node_4_io_out_0;
        CData/*1:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node_4_io_out_2;
        CData/*1:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node_5_io_out_0;
        CData/*1:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node_5_io_out_2;
        CData/*1:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node0_1_io_out_0;
        CData/*1:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node0_1_io_out_2;
        CData/*1:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node_8_io_out_0;
        CData/*1:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node_8_io_out_2;
        CData/*1:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node_9_io_out_0;
        CData/*1:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node_9_io_out_2;
        CData/*1:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node0_2_io_out_0;
        CData/*1:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node0_2_io_out_2;
        CData/*1:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node_12_io_out_0;
        CData/*1:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node_12_io_out_2;
        CData/*1:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node_13_io_out_0;
        CData/*1:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node0_3_io_out_0;
        CData/*1:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node0_3_io_out_2;
        CData/*1:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node0_4_io_out_0;
        CData/*1:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node0_4_io_out_2;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__n_0;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__p_1;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__z_1;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__p_3;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__p_4;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__z_4;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__p_6;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__p_7;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__z_7;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__p_9;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__p_10;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__z_10;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__p_12;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__p_13;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__z_13;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__p_15;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__p_16;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__z_16;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__p_18;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__p_19;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__z_19;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__p_21;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__p_22;
    };
    struct {
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__z_22;
        CData/*0:0*/ closePath__DOT__lza__DOT__errorDetector__DOT____VdfgTmp_hc1e9f2c8__0;
        CData/*0:0*/ closePath__DOT__lza__DOT__errorDetector__DOT____VdfgTmp_h2dd0dfe3__0;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node0__DOT__pout_0;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node0__DOT__pout_1;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node0__DOT__zout_0;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node0__DOT__zout_1;
        CData/*0:0*/ closePath__DOT__lza__DOT__errorDetector__DOT__y_node0__DOT____VdfgTmp_h4b5b1e37__0;
        CData/*0:0*/ closePath__DOT__lza__DOT__errorDetector__DOT__y_node0__DOT____VdfgTmp_h2627e8d8__0;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node__DOT__pout_0;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node__DOT__pout_1;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node__DOT__zout_0;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node__DOT__zout_1;
        CData/*0:0*/ closePath__DOT__lza__DOT__errorDetector__DOT__y_node__DOT____VdfgTmp_h4b5b1e37__0;
        CData/*0:0*/ closePath__DOT__lza__DOT__errorDetector__DOT__y_node__DOT____VdfgTmp_h2627e8d8__0;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node_1__DOT__pout_0;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node_1__DOT__pout_1;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node_1__DOT__zout_0;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node_1__DOT__zout_1;
        CData/*0:0*/ closePath__DOT__lza__DOT__errorDetector__DOT__y_node_1__DOT____VdfgTmp_h4b5b1e37__0;
        CData/*0:0*/ closePath__DOT__lza__DOT__errorDetector__DOT__y_node_1__DOT____VdfgTmp_h2627e8d8__0;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node_2__DOT__pout_0;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node_2__DOT__pout_1;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node_2__DOT__zout_0;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node_2__DOT__zout_1;
        CData/*0:0*/ closePath__DOT__lza__DOT__errorDetector__DOT__y_node_2__DOT____VdfgTmp_h4b5b1e37__0;
        CData/*0:0*/ closePath__DOT__lza__DOT__errorDetector__DOT__y_node_2__DOT____VdfgTmp_h2627e8d8__0;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node_3__DOT__pout_0;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node_3__DOT__pout_1;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node_3__DOT__zout_0;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node_3__DOT__zout_1;
        CData/*0:0*/ closePath__DOT__lza__DOT__errorDetector__DOT__y_node_3__DOT____VdfgTmp_h4b5b1e37__0;
        CData/*0:0*/ closePath__DOT__lza__DOT__errorDetector__DOT__y_node_3__DOT____VdfgTmp_h2627e8d8__0;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node_4__DOT__pout_0;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node_4__DOT__pout_1;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node_4__DOT__zout_0;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node_4__DOT__zout_1;
        CData/*0:0*/ closePath__DOT__lza__DOT__errorDetector__DOT__y_node_4__DOT____VdfgTmp_h4b5b1e37__0;
        CData/*0:0*/ closePath__DOT__lza__DOT__errorDetector__DOT__y_node_4__DOT____VdfgTmp_h2627e8d8__0;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node_5__DOT__pout_0;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node_5__DOT__pout_1;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node_5__DOT__zout_0;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node_5__DOT__zout_1;
        CData/*0:0*/ closePath__DOT__lza__DOT__errorDetector__DOT__y_node_5__DOT____VdfgTmp_h4b5b1e37__0;
        CData/*0:0*/ closePath__DOT__lza__DOT__errorDetector__DOT__y_node_5__DOT____VdfgTmp_h2627e8d8__0;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node_6__DOT__pout_0;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node_6__DOT__pout_1;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node_6__DOT__zout_0;
        CData/*0:0*/ closePath__DOT__lza__DOT__errorDetector__DOT__y_node_6__DOT____VdfgTmp_h4b5b1e37__0;
        CData/*0:0*/ closePath__DOT__lza__DOT__errorDetector__DOT__y_node_6__DOT____VdfgTmp_h2627e8d8__0;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node0_1__DOT__pout_0;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node0_1__DOT__pout_1;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node0_1__DOT__zout_0;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node0_1__DOT__zout_1;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node_7__DOT__pout_0;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node_7__DOT__pout_1;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node_7__DOT__zout_0;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node_7__DOT__zout_1;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node_8__DOT__pout_0;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node_8__DOT__pout_1;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node_8__DOT__zout_0;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node_8__DOT__zout_1;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node_9__DOT__pout_0;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node_9__DOT__pout_1;
    };
    struct {
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node_9__DOT__zout_0;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node_9__DOT__zout_1;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node_10__DOT__pout_0;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node_10__DOT__pout_1;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node_10__DOT__zout_0;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node_10__DOT__zout_1;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node0_2__DOT__pout_0;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node0_2__DOT__pout_1;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node0_2__DOT__zout_0;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node0_2__DOT__zout_1;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node_11__DOT__pout_0;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node_11__DOT__pout_1;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node_11__DOT__zout_0;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node_11__DOT__zout_1;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node_12__DOT__pout_0;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node_12__DOT__pout_1;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node_12__DOT__zout_0;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node_12__DOT__zout_1;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node_13__DOT__pout_0;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node_13__DOT__pout_1;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node_13__DOT__zout_0;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node_13__DOT__zout_1;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node0_3__DOT__pout_0;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node0_3__DOT__pout_1;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node0_3__DOT__zout_0;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node0_3__DOT__zout_1;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node_14__DOT__pout_0;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node_14__DOT__pout_1;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node_14__DOT__zout_0;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node_14__DOT__zout_1;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node0_4__DOT__pout_0;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node0_4__DOT__pout_1;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node0_4__DOT__zout_0;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node0_4__DOT__zout_1;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node_15__DOT__pout_0;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node_15__DOT__pout_1;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node_15__DOT__zout_0;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node_15__DOT__zout_1;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node0_5__DOT__pout_1;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node0_5__DOT__zout_0;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node0_5__DOT__zout_1;
        CData/*0:0*/ __PVT__closePath__DOT__lza__DOT__errorDetector__DOT__y_node0_6__DOT___pout_1_T_7;
        CData/*0:0*/ __PVT__closePath__DOT__near_path_tininess_rounder__DOT__rounder_io_signIn;
        CData/*0:0*/ __PVT__closePath__DOT__near_path_rounder__DOT__r_up;
        CData/*0:0*/ __VdfgTmp_h8093e782__0;
        CData/*0:0*/ __VdfgTmp_h4411a1c1__0;
        CData/*0:0*/ __VdfgTmp_haa69a3db__0;
        CData/*0:0*/ __VdfgTmp_h8a0d6673__0;
        CData/*0:0*/ __VdfgTmp_h27ccee37__0;
        CData/*0:0*/ __VdfgTmp_h803f76e4__0;
        CData/*0:0*/ __VdfgTmp_ha74c8422__0;
        CData/*0:0*/ __VdfgTmp_h0133aff4__0;
        CData/*0:0*/ __VdfgTmp_hb31c3312__0;
        VL_IN(io_in_bits_a,31,0);
        VL_IN(io_in_bits_b,31,0);
        VL_OUT(io_out_bits_result,31,0);
        IData/*23:0*/ __PVT__farPath_io_in_a_sig;
        IData/*23:0*/ __PVT__farPath_io_in_b_sig;
        IData/*23:0*/ __PVT__raw_a_sig;
        IData/*23:0*/ __PVT__raw_b_sig;
        IData/*26:0*/ __PVT__farPath__DOT__far_path_tininess_rounder_io_in_sig;
        IData/*26:0*/ __PVT__farPath__DOT___neg_sigB_T;
        IData/*27:0*/ __PVT__farPath__DOT__result_sig_raw;
        IData/*24:0*/ __PVT__closePath__DOT__lza_io_b;
    };
    struct {
        IData/*25:0*/ __PVT__closePath__DOT__resultSigComplementForm;
        IData/*24:0*/ __PVT__closePath__DOT__resultSigNoRound;
        IData/*24:0*/ __PVT__closePath__DOT__sig_s1;
        IData/*24:0*/ __PVT__closePath__DOT___near_path_sig_cor_T;
        IData/*24:0*/ __PVT__closePath__DOT__lza__DOT__preEncoder_io_f;
    };

    // INTERNAL VARIABLES
    VDotProdUnit__Syms* const vlSymsp;

    // CONSTRUCTORS
    VDotProdUnit_FADD(VDotProdUnit__Syms* symsp, const char* v__name);
    ~VDotProdUnit_FADD();
    VL_UNCOPYABLE(VDotProdUnit_FADD);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
